require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2

RSpec:
  Enabled: true

Layout/LineLength:
  IgnoreComments: true
  Max: 80

Metrics/ClassLength:
  Max: 300

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/ParameterLists:
  Max: 5

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GuardClause:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/EmptyMethod:
  Enabled: true

Style/EmptyBlockParameter:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Style/MutableConstant:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/Debugger:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/MethodName:
  Enabled: true

Naming/VariableName:
  Enabled: true

Layout/IndentationWidth:
  Width: 2

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/TrailingCommaInHashLiteral:
  EnforcedStyle: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyle: consistent_comma

Security/Eval:
  Enabled: true

Security/Open:
  Enabled: true

Security/YAMLLoad:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true
